{% set name = "pyobjc-framework-applicationservices" %}
{% set version = "10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 36ca55df6a9552b7404e1a0799797c15db47faf608050024a898d50d2b1f4351

build:
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - pyobjc-core >={{ version }}
    - pyobjc-framework-cocoa >={{ version }}
    - pyobjc-framework-quartz >={{ version }}
    - pyobjc-framework-CoreText >={{ version }}

test:
  imports:
    - PyObjCTools
    - ApplicationServices
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework ApplicationServices on macOS
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - rxm7706
